// Single point to swap icon library.
// To replace @tabler/icons-react: update imports here only.
export {
  IconPlus,
  IconEdit,
  IconTrash,
  IconSearch,
  IconX,
  IconLayoutDashboard,
  IconTag,
  IconLogout,
  IconMenu2,
  IconSun,
  IconMoon,
  IconCheck,
  IconAlertTriangle,
  IconInfoCircle,
  IconCircleX,
  IconApps,
  IconEye,
  IconEyeOff,
  IconArrowLeft,
  IconLogin2,
  IconPackage,
  IconCategory,
  IconShoppingCart,
  IconChevronLeft,
  IconChevronRight,
  IconWorld,
  IconBrandFacebook,
  IconBrandX,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandYoutube,
  IconBrandTiktok,
  IconBrandWhatsapp,
  IconBrandTelegram,
  IconBrandGithub,
  IconBrandPinterest,
} from '@tabler/icons-react';
