// Single point to swap icon library.
// To replace @tabler/icons-react: update imports here only.
export {
  IconPlus,
  IconEdit,
  IconTrash,
  IconSearch,
  IconX,
  IconLayoutDashboard,
  IconTag,
  IconLogout,
  IconMenu2,
  IconSun,
  IconMoon,
  IconCheck,
  IconAlertTriangle,
  IconInfoCircle,
  IconCircleX,
  IconApps,
  IconEye,
  IconArrowLeft,
  IconPackage,
  IconShoppingCart,
  IconChevronLeft,
  IconChevronRight,
} from '@tabler/icons-react';
